# Generated by Django 4.2.2 on 2023-06-27 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_project_image_1_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="review_user",
        ),
    ]
