# Generated by Django 4.2.2 on 2023-06-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='v1687582654/profiles/user-default.jpg', null=True, upload_to='profiles'),
        ),
    ]
